// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrumpVerseAPI.Models;

#nullable disable

namespace TrumpVerseAPI.Migrations
{
    [DbContext(typeof(TrumpVerseContext))]
    [Migration("20241212103428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TrumpVerseAPI.Models.TrumpStaff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfHire")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TrumpStaffs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateOfHire = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "donald@trumpverse.com",
                            FirstName = "Donald",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Trump",
                            PhoneNumber = "123456789",
                            ProfilePicture = "/images/Donald-Trump.jpg",
                            Role = "President"
                        },
                        new
                        {
                            ID = 2,
                            DateOfHire = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "JD@trumpverse.com",
                            FirstName = "JD",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Vance",
                            PhoneNumber = "123456789",
                            ProfilePicture = "/images/Vance.jpg",
                            Role = "Vice President"
                        },
                        new
                        {
                            ID = 3,
                            DateOfHire = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Scott@trumpverse.com",
                            FirstName = "Scott",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Bessent",
                            PhoneNumber = "123456789",
                            ProfilePicture = "/images/Scott-Turner.jpg",
                            Role = "SOT Treasury"
                        },
                        new
                        {
                            ID = 4,
                            DateOfHire = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pam@trumpverse.com",
                            FirstName = "Pam",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Bondi",
                            PhoneNumber = "123456789",
                            ProfilePicture = "/images/Bondi.jpg",
                            Role = "Atourney General"
                        },
                        new
                        {
                            ID = 5,
                            DateOfHire = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "brooke@trumpverse.com",
                            FirstName = "Brooke",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Rollins",
                            PhoneNumber = "123456789",
                            ProfilePicture = "/images/Brooke-Rollins.jpg",
                            Role = "SOT Agriculture"
                        },
                        new
                        {
                            ID = 6,
                            DateOfHire = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lori@trumpverse.com",
                            FirstName = "Lori",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "DeRemer",
                            PhoneNumber = "123456789",
                            ProfilePicture = "/images/Lori-Chaves.jpg",
                            Role = "SOT Labor"
                        },
                        new
                        {
                            ID = 7,
                            DateOfHire = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Scott@trumpverse.com",
                            FirstName = "Scott",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Turner",
                            PhoneNumber = "123456789",
                            ProfilePicture = "/images/Scott-Turner.jpg",
                            Role = "SOT Urban Development"
                        },
                        new
                        {
                            ID = 8,
                            DateOfHire = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chris@trumpverse.com",
                            FirstName = "Chris",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Wright",
                            PhoneNumber = "123456789",
                            ProfilePicture = "/images/Chris-Wright.jpg",
                            Role = "SOT Energy"
                        },
                        new
                        {
                            ID = 9,
                            DateOfHire = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "doug@trumpverse.com",
                            FirstName = "Doug",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Collins",
                            PhoneNumber = "123456789",
                            ProfilePicture = "/images/Doug-Collins.jpg",
                            Role = "SOT Veterans Affairs"
                        },
                        new
                        {
                            ID = 10,
                            DateOfHire = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kristi@trumpverse.com",
                            FirstName = "Kristi",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Noem",
                            PhoneNumber = "123456789",
                            ProfilePicture = "/images/Noem.jpg",
                            Role = "Governor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
